package enums;

public enum ModulePages {
	HOMEPAGE,
	LOGINPAGE,
	SEARCHPAGE,
	PRODUCTDISPLAYPAGE,
	PRODUCTDETAILPAGE,
	REGISTRATIONPAGE,
	MYPROFILEPAGE,
	RESETPASSWORDPAGE,
	MYORGANIZATIONPAGE,
	TWOFACTORAUTHENTICATIONPAGE, 
	PRODUCTLISTPAGE, 
	ACCOUNTDASHBOARDPAGE, 
	CARTPAGE, 
	LOCATIONSPAGE, USERPROFILEPAGE,
}
